name: Update GitHub Stats Cards

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub stats cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: >-
            username=brandonwie&show_icons=true&theme=midnight-purple&hide=stars&custom_title=Brandon%27s%20GitHub%20Stats&include_all_commits=true&show=reviews,prs_merged
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "ci: update GitHub stats cards" || exit 0
          git push
